### ISSUE TITLE
Broken link on Security page in SciDB 16.9 docs

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/SciDB#17]
On the [Security](https://paradigm4.atlassian.net/wiki/display/ESD169/Security) page, [load the namespaces library](https://paradigm4.atlassian.net/wiki/display/SD/load_library) points to a link which redirects to the Atlassian authentication page. Probably the page does not exist. The correct link is might be to the [load_library](https://paradigm4.atlassian.net/wiki/display/ESD169/load_library) operator.

**Comment by ksens** [comment]
Thanks @rvernica 

Fixed the broken link (was pointing to a private facing link). Please check and close the issue.

**Comment by rvernica** [comment]
Here is another similar issue, on the [add_instances](https://paradigm4.atlassian.net/wiki/spaces/ESD169/pages/50856264/add+instances) page, the [Managing SciDB Instances](https://paradigm4.atlassian.net/wiki/display/SD/Managing+SciDB+Instances#ManagingSciDBInstances-AddingAdditionalInstances) link at the bottom.

**Comment by ksens** [comment]
@rvernica I made the edit. Please check.
