### ISSUE TITLE
SciDB 14.3: load_csv.py fails for "|" delimited files

### ISSUE THREAD

**Issue by mikehwang** [Paradigm4/SciDB#2]
`load_csv.py` just hangs when trying to execute this:

```
Starting CSV distribution and conversion processes.
   cat "/tmp/test_sample_l_0000" | ssh -c arcfour256 127.0.0.1 \"/opt/scidb/14.3/bin/csv2scidb\" -p \"SNNNNNNNNN\" -c 500000 -f 0 -n 2 -d \"|\" -o \"/home/scidb/scidbdata/000/0/test_sample_l.dlf\"
   cat "/tmp/test_sample_l_0001" | ssh -c arcfour256 127.0.0.1 \"/opt/scidb/14.3/bin/csv2scidb\" -p \"SNNNNNNNNN\" -c 500000 -f 500000 -n 2 -d \"|\" -o \"/home/scidb/scidbdata/000/1/test_sample_l.dlf\"
```

The last log lines are:

```
A simple SciDB web interface is available by directing your browser to:
https://10.0.2.15:8083

Start using RStudio and the SciDB-R package by pointing your browser to:
http://10.0.2.15:8787

Start using Python and the SciDB-Py package by pointing your browser to:
https://10.0.2.15:8888

Or, log in below as the scidb user to start using SciDB at the command line.

LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.5 (Final)
Release:        6.5
Codename:       Final
bash: -c: line 0: unexpected EOF while looking for matching `"'
bash: -c: line 1: syntax error: unexpected end of file
bash: -c: line 0: unexpected EOF while looking for matching `"'
bash: -c: line 1: syntax error: unexpected end of file
```

The issue is with the attempted character escaping in the ssh command.  If you get rid of the character escaping and wrap the whole remote command with a single quote, the ssh command works.

I would fix this but SciDB is not open to community contribution.

**Comment by apoliakov** [comment]
Hi. Thanks. We decided that load-over-ssh in general was giving us too many problems. So we replaced loadcsv with tools like this: https://github.com/paradigm4/load_tools

If you like, you can give us code patches and we will surely review them for inclusion into the code base.

**Comment by mikehwang** [comment]
Thanks for replying.

I'm using v14.3 and running the quickstart VirtualBox image provided.  I looked into using [load_tools](https://github.com/paradigm4/load_tools) and attempted to build it because 14.3 doesn't include it.  The build was failing on the box and I didn't want to go through the trouble of debugging it.

The 14.3 documents recommends using `load_csv.py` for parallel loading.

I'm testing SciDB as a possible database solution.  I need to load 400 3GB files.  What is the most reliable way to do this?

Regarding the patch, how do I submit my changes?

**Comment by apoliakov** [comment]
Yeah 14.3 was almost two years ago. We made a lot of improvements since then. I definitely recommend using 15.7 over 14.3. Note there's a fair amount of docker work out there. For example: https://hub.docker.com/r/cerbo/scidb/
And this isn't the only one I'm aware of.

With 15.7 (p4) we have some customers who are loading ~1TB per day (using accelerated p4 loader). Assuming the data is delimited text - I recommend load_tools, or talk to us if you want the accelerated extensions.

If you want to submit a patch - feel free to put it in the body of a ticket here and we'll evaluate it. But we retired loadcsv a long time ago, so making changes to that code wouldn't be a very high priority item for us.

**Comment by mikehwang** [comment]
1TB/day is definitely the scale my company needs and as I mentioned I am doing performance and functional testing of SciDB.  Is there a sales engineering team that could help me?  What's the most effective way to get help?  Setting up a test bed has not been an easy process for me.

I looked into the [docker option](https://github.com/Paradigm4/docker_scidb) but I think the implementation is flawed.  My understanding is that good practice is that each container should be running one application because docker is meant to be used as an application container.  The docker images I've seen for SciDB violates this.  A side effect of this violation is the fact that I can't use the docker images to run a cluster.

**Comment by apoliakov** [comment]
Mike I think I just found you and emailed you
In case you don't get the email, I am apoliakov [at] paradigm4 [dot] com
