### ISSUE TITLE
run.py install uses stage_path for DB location

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/SciDB#4]
The `install` function in the `run.py` uses `stage_path` to build the path for the DB (`data_path`). Shouldn't it be using `install_path` instead?

This [gist](https://gist.github.com/rvernica/cec79b7000813704a6f622f0b372c229/revisions) is a patched `run.py` to address this issue.

This issues is both in `15.7` and `15.12` scripts.

**Comment by apoliakov** [comment]
Thx! Forwarded to the dev guys to take a look

**Comment by dzhangp4** [comment]
run.py is a developer tool. The common use case is that all of build path, install path, and data path are inside some stage. For different branches, you may have different stages. That being said, all these paths may be altered. If you type "run.py -h" and "run.py install -h" you'll see SCIDB_BUILD_PATH, SCIDB_INSTALL_PATH, and SCIDB_DATA_PATH. You for instance may call run.py as follows to put the data path in a subdir of the install path:

SCIDB_DATA_PATH=$SCIDB_INSTALL_PATH/data  run.py install

**Comment by rvernica** [comment]
I see. OK, thanks!
