### ISSUE TITLE
Typo in 16.9 docs - list and point to 15.12 src

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/SciDB#6]
The SciDB `16.9` documentation, in *Pre-Installation Tasks* https://paradigm4.atlassian.net/wiki/display/ESD169/Pre-Installation+Tasks, states:

> Access the 15.12 CE page and download the 15.12 source code tarball.

The link also points to `15.12` source.

**Comment by apoliakov** [comment]
Looks like this has been fixed
