### ISSUE TITLE
Error building src/system/Constants.cpp in 16.9

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/SciDB#7]
Compiling SciDB `16.9` from `scidb-16.9.0.db1a98f.tgz` results in an error when compiling `src/system/Constants.cpp`:
```
/usr/src/scidb/stage/build/src/system/Constants.cpp:45:45: error: integer constant is too large for its type [-Werror]
 uint32_t    SCIDB_VERSION_BUILD()   {return 0xdb1a98ff4202a1a4ffc6a677ae5156323a5ad90c;}
                                             ^
/usr/src/scidb/stage/build/src/system/Constants.cpp: In function 'uint32_t scidb::SCIDB_VERSION_BUILD()':
/usr/src/scidb/stage/build/src/system/Constants.cpp:45:45: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
cc1plus: all warnings being treated as errors
```

The return value of the `SCIDB_VERSION_BUILD` function is set by `cmake`, by expanding the `CONFIGURE_SCIDB_VERSION_BUILD` variable in `src/system/Constants.cpp.in`. The `CONFIGURE_SCIDB_VERSION_BUILD` variable is set by expanding `SCIDB_REVISION` in `src/system/CMakeList.txt`. Finally, the `SCIDB_REVISION` variable is set in the root `CMakeList.txt` file, by reading the `revision` file, see [line 84](https://gist.github.com/rvernica/3edf4b95e4f957d9d5410ff43bfeb5ff/6cb6636c217620f255efa005fb35acfa4d77de21#file-cmakelists-txt-L84). The value in the `revision` file is `db1a98ff4202a1a4ffc6a677ae5156323a5ad90c`.

If the directory is a Git repository, the `SCIDB_REVISION` variable is set to the last revision of the repository, see [line 76](https://gist.github.com/rvernica/3edf4b95e4f957d9d5410ff43bfeb5ff/6cb6636c217620f255efa005fb35acfa4d77de21#file-cmakelists-txt-L67). Notice how the abbreviated commit hash is retrieved using `--abbrev-commit`. So, this error won't arise if the directory is a Git repository.

In the case where the value from the `revision` file is used, this error can be fixed using `SUBSTRING` in `CMakeList.txt` and extracting only the first `7` characters of the hash:
```
string(SUBSTRING ${SCIDB_REVISION} 0 7 SCIDB_REVISION)
```
See [here](https://gist.github.com/rvernica/3edf4b95e4f957d9d5410ff43bfeb5ff/revisions?diff=unified#diff-af3b638bc2a3e6c650974192a53c7291) for a diff of `CMakeList.txt` after making this change.

**Comment by apoliakov** [comment]
Thanks, going to have folks look at this.

**Comment by apoliakov** [comment]
We just uploaded an updated tarball - should have this issue fixed
