### ISSUE TITLE
Bash compatiblity issue in run.py

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/SciDB#8]
This is not necessarily a bug, but a compatibility issue. In `run.py`, the `getScidbVersion` function uses the `|&` redirect operator in [line 479](https://gist.github.com/rvernica/47cc98fd728156657922920caafc01d3/35da010d764f98b213e31d74941eef87dfb75510#file-run-py-L479). Moreover, the command is executed using the default `/bin/sh` shell.

If `/bin/sh` is symbolic link to Bash, the code executes OK. If `/bin/sh` is linked to Dash, the code fails due to the `|&` redirect. Here is an example:
```python
# readlink -f /bin/sh
/bin/dash
# python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import run
>>> run.executeIt(['/usr/src/scidb/deployment/deploy.sh', 'usage', '|&', 'grep', '"SciDB version"'], useShell=True, collectOutput=True, cwd='/usr/src/scidb')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "run.py", line 292, in executeIt
    raise RuntimeError("Abnormal return code: %s on command %s" % (ret, cmdList))
RuntimeError: Abnormal return code: 2 on command ['/usr/src/scidb/deployment/deploy.sh usage |& grep "SciDB version"']
# sh
# /usr/src/scidb/deployment/deploy.sh usage |& grep "SciDB version"
sh: 1: Syntax error: "&" unexpected
```
So, the script uses the `|&` operator which is mainly supported by Bash and assumes that the default shell `/bin/sh` is Bash. There are two ways to fix this.

1. Specify a shell to use using the `cmd` parameter:
   ```python
   >>> run.executeIt(['/usr/src/scidb/deployment/deploy.sh', 'usage', '|&', 'grep', '"SciDB version"'],   useShell=True, collectOutput=True, cwd='/usr/src/scidb', cmd='bash')
   (0, 'SciDB version: 16.9\n', '')
   ```
1. Expand `|&` to the more portable `2>&1 |`:
   ```python
   >>> run.executeIt(['/usr/src/scidb/deployment/deploy.sh', 'usage', '2>&1', '|', 'grep', '"SciDB version"'], useShell=True, collectOutput=True, cwd='/usr/src/scidb')
   (0, 'SciDB version: 16.9\n', '')
   ```
   A diff of `run.py` with this change applied is available [here](https://gist.github.com/rvernica/47cc98fd728156657922920caafc01d3/revisions?diff=unified#diff-6e38f16215ae91c11fc5c54b74c66d54).

**Comment by apoliakov** [comment]
Should be fixed with the new tarball - see also https://github.com/Paradigm4/SciDB/issues/7
